#!/usr/bin/env bash

source ./init_scripts

install() {
  install_base_utils
  install_ohmyposh
  install_vscodium
  install_nvm
  install_go
  install_pyenv
  link_dotfiles
  setup_git_authorship
}

install
