#!/usr/bin/env bash

source ./init_scripts

install() {
    install_base_utils
    install_mise
    install_mise_tools
    install_ohmyposh
    link_dotfiles
    setup_git_authorship
    setup_git_ignore
}

install
