#!/usr/bin/env bash
# Add vscodium extensions

# Git graph
codium --install-extension mhutchie.git-graph
# Prettier
codium --install-extension esbenp.prettier-vscode
# Pretty TS errors
codium --install-extension yoavbls.pretty-ts-errors
# Eslint
codium --install-extension dbaeumer.vscode-eslint
# Python tools
codium --install-extension ms-python.python
# Go tools
codium --install-extension golang.go
# Catpuccin theme
codium --install-extension catppuccin.catppuccin-vsc-icons
# Srcery theme
codium --install-extension srcery-colors.srcery-colors
