#!/usr/bin/env bash

# Fonts to pull from nerd-font
mkdir -p ~/.local/share/fonts

# in case it already existed
rm -rf ~/.local/share/fonts/*

cd ~/.local/share/fonts

# font symbols
curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf

# intel one mono font
curl -fLO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/IntelOneMono.zip
unzip IntelOneMono.zip -d IntelOneMono

rm IntelOneMono.zip
